SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{69733123121BFC36}" {
   m_Info SCR_UIInfo "{69733120E0BA1267}" {
    Name "HAF"
    Icon "{1C98A392552CB2B6}UI/HAF_Flag_Icon_BCR.edds"
   }
   m_LabelType FACTION_HAF
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{697736FDF9BBBC8B}" {
   m_Info SCR_UIInfo "{697736FDF9BBBCCE}" {
    Name "HTC"
    Icon "{1AA6F41671C7EAFD}UI/HTC_Flag_Icon_BCR.edds"
   }
   m_LabelType FACTION_HTC
   m_LabelGroupType FACTION
  }
 }
}