SCR_MissionHeader {
 World "{DF091602D62C62CC}Worlds/Arland/Demo.ent"
 m_sName "Triad Hauriya Factions Demo World"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "A faction mod set in Hauriya — a fictional Middle Eastern country torn apart by civil war and foreign interests"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}