SCR_Faction {
 FactionKey "HAF"
 FactionColor 0.016 0.552 0.905 1
 UIInfo SCR_FactionUIInfo "{6973312C97D4174F}" {
  Name "#THF-Factions_HAF"
  Icon "{1C98A392552CB2B6}UI/HAF_Flag_Icon_BCR.edds"
 }
 "Identity of soldiers" FactionIdentity "{6973312D0C399939}" : "{451B93116D3BA72D}Configs/Identities/FactionIdentity_Arab.conf" {
 }
 "Radio encryption key" "hafRadio"
 m_OutlineFactionColor 0.005 0.044 0.114 1
 m_NotificationFactionColor 0.016 0.552 0.905 1
 m_NotificationTextFactionColor 0.013 0.395 0.651 1
 m_sFactionFlag "{859425038F03A10D}UI/HAF_Flag_800400_BCR.edds"
 m_FactionFlagMaterial "{050A26B2EA96CFE9}Assets/Props/Fabric/Flags/Data/Flag_1_2_HAF.emat"
 m_FactionLabel FACTION_HAF
 m_CallsignInfo SCR_FactionCallsignInfo "{69733122CC46E609}" : "{FE5EC3F3127820DF}Configs/Callsigns/Callsigns_Arab.conf" {
 }
 m_iFactionRadioFrequency 48000
 m_sGroupFlagsImageSet "{1228936E5DB30403}UI/Textures/GroupManagement/FlagIcons/GroupFlagsBlufor.imageset"
 m_sGroupFlagsImageSetOutlines "{D1BFDF90DD7A4E01}UI/Textures/GroupManagement/FlagIcons/GroupFlagsBlufor-outline.imageset"
 m_aFlagNames {
  "infantry"
  "amphibious"
  "anti-air"
  "anti-air-artilery"
  "anti-armor-motorized"
  "antiarmor"
  "armored"
  "artillery"
  "combined"
  "helicopter"
  "helicopter-attack"
  "infantry-air"
  "machinegun"
  "maintenance"
  "medical"
  "mortar"
  "motorized"
  "motorized-infantry"
  "recon"
  "recon-motorized"
  "signal"
  "sniper"
  "supply-motorized"
  "undefined"
  "commander"
  "special-forces"
 }
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{697331228DAF16C0}" : "{D210F8AB0479C560}Configs/Identities/Territories/FactionHomeTerritory_Arab.conf" {
 }
}