SCR_Faction {
 FactionKey "HTC"
 FactionColor 0.098 0.1961 0.3922 1
 UIInfo SCR_FactionUIInfo "{697736F4EDF0B181}" {
  Name "#THF-Factions_HTC"
  Icon "{1AA6F41671C7EAFD}UI/HTC_Flag_Icon_BCR.edds"
 }
 "Identity of soldiers" FactionIdentity "{6973312D0C399939}" : "{451B93116D3BA72D}Configs/Identities/FactionIdentity_Arab.conf" {
 }
 "Radio encryption key" "htcRadio"
 m_OutlineFactionColor 0.039 0.098 0.196 1
 m_NotificationFactionColor 0.098 0.196 0.392 1
 m_NotificationTextFactionColor 0.922 0.922 0.922 1
 m_sFactionFlag "{03EC3EB73461EEF8}UI/HTC_Flag_800400_BCR.edds"
 m_FactionFlagMaterial "{5E410EB0B7924CD0}Assets/Props/Fabric/Flags/Data/Flag_1_2_HTC.emat"
 m_FactionLabel FACTION_HTC
 m_CallsignInfo SCR_FactionCallsignInfo "{69733122CC46E609}" : "{FE5EC3F3127820DF}Configs/Callsigns/Callsigns_Arab.conf" {
 }
 m_iFactionRadioFrequency 50000
 m_sGroupFlagsImageSet "{1228936E5DB30403}UI/Textures/GroupManagement/FlagIcons/GroupFlagsBlufor.imageset"
 m_sGroupFlagsImageSetOutlines "{D1BFDF90DD7A4E01}UI/Textures/GroupManagement/FlagIcons/GroupFlagsBlufor-outline.imageset"
 m_aFlagNames {
  "infantry"
  "amphibious"
  "anti-air"
  "anti-air-artilery"
  "anti-armor-motorized"
  "antiarmor"
  "armored"
  "artillery"
  "combined"
  "helicopter"
  "helicopter-attack"
  "infantry-air"
  "machinegun"
  "maintenance"
  "medical"
  "mortar"
  "motorized"
  "motorized-infantry"
  "recon"
  "recon-motorized"
  "signal"
  "sniper"
  "supply-motorized"
  "undefined"
  "commander"
  "special-forces"
 }
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{697331228DAF16C0}" : "{D210F8AB0479C560}Configs/Identities/Territories/FactionHomeTerritory_Arab.conf" {
 }
}