EditablePrefabsComponent_EditableEntity {
 m_EntityLabelRules {
  EditablePrefabsLabel_Faction "{697331216ADA40EC}" {
   m_Label FACTION_HAF
   m_FactionToCheck "HAF"
  }
  EditablePrefabsLabel_Faction "{697736F21D95C229}" {
   m_Label FACTION_HTC
   m_FactionToCheck "HTC"
  }
 }
}