StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6973312E30327E2D}" {
   Id "THF-Characters_Rifleman"
   Target_en_us "Rifleman"
   Modified 1769159144
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6973312C6AA310A1}" {
   Id "THF-Factions_HAF"
   Target_en_us "HAF"
   Modified 1769159917
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}