StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6974BB2F9A37309B}" {
   Id "THF-Characters_AAT"
   Target_en_us "Assistant Anti-Tank"
   Modified 1769276185
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB1A31FF7B70}" {
   Id "THF-Characters_AMG"
   Target_en_us "Assistant Machine Gunner"
   Modified 1769265985
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB1E988F4242}" {
   Id "THF-Characters_AT"
   Target_en_us "Rifleman Anti-Tank"
   Modified 1769267889
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6975222B44D0906D}" {
   Id "THF-Characters_Civilian"
   Target_en_us "Civilian"
   Modified 1769285362
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69752229B75CB742}" {
   Id "THF-Characters_Civilian_SL"
   Target_en_us "Civilian (Leader)"
   Modified 1769284303
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{697736E7ABFB9344}" {
   Id "THF-Characters_Crewman"
   Target_en_us "Crewman"
   Modified 1769428504
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB2D8C392F66}" {
   Id "THF-Characters_DPL"
   Target_en_us "Deputy Platoon Leader"
   Modified 1769277069
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB1A9D26B478}" {
   Id "THF-Characters_MG"
   Target_en_us "Machine Gunner"
   Modified 1769265787
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{697736E7211ED2FC}" {
   Id "THF-Characters_Mukhabarat"
   Target_en_us "Mukhabarat Officer"
   Modified 1769428759
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB2DB4D87EB9}" {
   Id "THF-Characters_PL"
   Target_en_us "Platoon Leader"
   Modified 1769277050
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69750BE27643F4A1}" {
   Id "THF-Characters_Prisoner"
   Target_en_us "Prisoner"
   Modified 1769282997
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6973312E30327E2D}" {
   Id "THF-Characters_Rifleman"
   Target_en_us "Rifleman"
   Modified 1769159144
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB0DC14B3BD8}" {
   Id "THF-Characters_Rifleman_AT"
   Target_en_us "Rifleman (AT)"
   Modified 1769261288
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB0673472DF9}" {
   Id "THF-Characters_SL"
   Target_en_us "Squad Leader"
   Modified 1769264031
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB2C8C6C9C76}" {
   Id "THF-Characters_Sniper"
   Target_en_us "Sniper"
   Modified 1769276608
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB05EB9A7235}" {
   Id "THF-Characters_SR"
   Target_en_us "Senior Rifleman"
   Modified 1769265132
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6973312C6AA310A1}" {
   Id "THF-Factions_HAF"
   Target_en_us "HAF"
   Modified 1769159917
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{697736F47E932F31}" {
   Id "THF-Factions_HTC"
   Target_en_us "HTC"
   Modified 1769422173
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6975222C07801E1C}" {
   Id "THF-Groups_Civilians"
   Target_en_us "Civilians"
   Modified 1769286849
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB2394122F58}" {
   Id "THF-Groups_HQ"
   Target_en_us "Platoon HQ"
   Modified 1769278026
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{697736E5D5F4B741}" {
   Id "THF-Groups_Mukhabarat"
   Target_en_us "Mukhabarat"
   Modified 1769429405
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69750BEF87119C8B}" {
   Id "THF-Groups_Prisoners"
   Target_en_us "Prisoners"
   Modified 1769283010
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6974BB22576D4239}" {
   Id "THF-Groups_RifleSquad"
   Target_en_us "Rifle Squad"
   Modified 1769277676
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}