SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{69733122FD58AF4E}" {
   m_sCallsign "#AR-Callsign_US_Company_A"
  }
  SCR_CallsignInfo "{69733122FD58AF75}" {
   m_sCallsign "#AR-Callsign_US_Company_B"
  }
  SCR_CallsignInfo "{69733122FD58AF77}" {
   m_sCallsign "#AR-Callsign_US_Company_C"
  }
  SCR_CallsignInfo "{69733122FD580479}" {
   m_sCallsign "#AR-Callsign_US_Company_D"
  }
  SCR_CallsignInfo "{69733122FD580478}" {
   m_sCallsign "#AR-Callsign_US_Company_E"
  }
  SCR_CallsignInfo "{69733122FD580477}" {
   m_sCallsign "#AR-Callsign_US_Company_F"
  }
  SCR_CallsignInfo "{69733122FD580476}" {
   m_sCallsign "#AR-Callsign_US_Company_G"
  }
  SCR_CallsignInfo "{69733122FD582A9A}" {
   m_sCallsign "#AR-Callsign_US_Company_H"
  }
 }
 m_aPlatoonNames {
  SCR_CallsignInfo "{69733122FD582A99}" {
   m_sCallsign "#AR-Callsign_US_Platoon_1"
  }
  SCR_CallsignInfo "{69733122FD582A98}" {
   m_sCallsign "#AR-Callsign_US_Platoon_2"
  }
  SCR_CallsignInfo "{69733122FD582A9F}" {
   m_sCallsign "#AR-Callsign_US_Platoon_3"
  }
  SCR_CallsignInfo "{69733122FD5997C4}" {
   m_sCallsign "#AR-Callsign_US_Platoon_4"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{69733122FD5997C5}" {
   m_sCallsign "1"
  }
  SCR_CallsignInfo "{69733122FD5997DC}" {
   m_sCallsign "2"
  }
  SCR_CallsignInfo "{69733122FD5997DD}" {
   m_sCallsign "3"
  }
  SCR_CallsignInfo "{69733122FD5997DE}" {
   m_sCallsign "4"
  }
 }
 m_sCallsignGroupFormat "%1 %2 %3"
 m_sCallsignCharacterFormat "%1 %2 %3: %4"
 m_sCallsignCharacterWithRoleFormat "%1 %2 %3: %4"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{69733122FD5997DF}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{69733122FD5997D0}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{69733122FD59A1B4}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}