SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadHauriyaFactions"
 m_sSourceDirectory "{B3F42CE5D0725435}Prefabs/Characters/Factions/HAF"
 m_bExposed 1
 m_Prefabs {
  "{00A961D174C29C85}Prefabs/Characters/Factions/HAF/Character_HAF_Rifleman.et"
  "{22C81F3E1C1A854E}Prefabs/Characters/Factions/HAF/Character_HAF_Rifleman_AT.et"
  "{605195B00534A672}Prefabs/Characters/Factions/HAF/Character_HAF_SL.et"
  "{1D49794860A79AEB}Prefabs/Characters/Factions/HAF/Character_HAF_SR.et"
  "{5FCEBAB559FF1082}Prefabs/Characters/Factions/HAF/Character_HAF_MG.et"
  "{D11A8EEB636C6640}Prefabs/Characters/Factions/HAF/Character_HAF_AMG.et"
  "{D5710D6E4E391A3D}Prefabs/Characters/Factions/HAF/Character_HAF_AT.et"
  "{5BA5393074AA6CFF}Prefabs/Characters/Factions/HAF/Character_HAF_AAT.et"
  "{8F38AF87D0954830}Prefabs/Characters/Factions/HAF/Character_HAF_Sniper.et"
  "{F94F2C2918D397E2}Prefabs/Characters/Factions/HAF/Character_HAF_PL.et"
  "{94A363B3E2D67331}Prefabs/Characters/Factions/HAF/Character_HAF_DPL.et"
  "{D9626FAAF46209E0}Prefabs/Characters/Factions/HAF/Prisoners/Character_HAF_Prisoner_1.et"
  "{9491E7AD79247613}Prefabs/Characters/Factions/HAF/Prisoners/Character_HAF_Prisoner_2.et"
  "{710DAB5475C1E178}Prefabs/Characters/Factions/HAF/Prisoners/Character_HAF_Prisoner_3.et"
  "{4C398E6C00AD684F}Prefabs/Characters/Factions/HAF/Prisoners/Character_HAF_Prisoner_4.et"
  "{A9A5C2950C48FF24}Prefabs/Characters/Factions/HAF/Prisoners/Character_HAF_Prisoner_5.et"
  "{C5F1F675B08C700A}Prefabs/Characters/Factions/HAF/Prisoners/Character_HAF_Prisoner_6.et"
  "{206DBA8CBC69E761}Prefabs/Characters/Factions/HAF/Prisoners/Character_HAF_Prisoner_7.et"
  "{BF99BC055A556264}Prefabs/Characters/Factions/HAF/Prisoners/Character_HAF_Prisoner_8.et"
  "{5B7E704D3C53F348}Prefabs/Characters/Factions/HAF/Civilian/Character_HAF_Civilian_SL.et"
  "{4FBB69AE32BB46CA}Prefabs/Characters/Factions/HAF/Civilian/Character_HAF_Civilian_1.et"
  "{23EF5D4E8E7FC9E4}Prefabs/Characters/Factions/HAF/Civilian/Character_HAF_Civilian_2.et"
  "{C67311B7829A5E8F}Prefabs/Characters/Factions/HAF/Civilian/Character_HAF_Civilian_3.et"
  "{FB47348FF7F6D7B8}Prefabs/Characters/Factions/HAF/Civilian/Character_HAF_Civilian_4.et"
  "{1EDB7876FB1340D3}Prefabs/Characters/Factions/HAF/Civilian/Character_HAF_Civilian_5.et"
  "{728F4C9647D7CFFD}Prefabs/Characters/Factions/HAF/Civilian/Character_HAF_Civilian_6.et"
  "{9713006F4B325896}Prefabs/Characters/Factions/HAF/Civilian/Character_HAF_Civilian_7.et"
 }
}