SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadHauriyaFactions"
 m_sSourceDirectory "{B3F42CE5D0725435}Prefabs/Characters/Factions/HAF"
 m_bExposed 1
 m_Prefabs {
  "{00A961D174C29C85}Prefabs/Characters/Factions/HAF/Character_HAF_Rifleman.et"
 }
}