SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadHauriyaFactions"
 m_sSourceDirectory "{C91242B24E07047A}Prefabs/Characters/Factions/HTC"
 m_bExposed 1
 m_Prefabs {
  "{E835B6A414CE4915}Prefabs/Characters/Factions/HTC/Character_HTC_Rifleman.et"
  "{3F4FD0F4DDD32284}Prefabs/Characters/Factions/HTC/Character_HTC_RiflemanAT.et"
  "{30B322072B4F7340}Prefabs/Characters/Factions/HTC/Character_HTC_SL.et"
  "{A9AD9B9E36A842D0}Prefabs/Characters/Factions/HTC/Character_HTC_PL.et"
  "{CA2CAE77E38EE5F1}Prefabs/Characters/Factions/HTC/Character_HTC_DPL.et"
  "{4DABCEFF4EDC4FD9}Prefabs/Characters/Factions/HTC/Character_HTC_SR.et"
  "{8F95432F6234F080}Prefabs/Characters/Factions/HTC/Character_HTC_AMG.et"
  "{052AF4F475F2FA3F}Prefabs/Characters/Factions/HTC/Character_HTC_AAT.et"
  "{8593BAD96042CF0F}Prefabs/Characters/Factions/HTC/Character_HTC_AT.et"
  "{0F2C0D027784C5B0}Prefabs/Characters/Factions/HTC/Character_HTC_MG.et"
  "{F0388C32B8764695}Prefabs/Characters/Factions/HTC/Character_HTC_Sniper.et"
  "{A0175D595212B7CC}Prefabs/Characters/Factions/HTC/Character_HTC_Crewman.et"
  "{661781E683DE9149}Prefabs/Characters/Factions/HTC/Character_HTC_Mukhabarat.et"
 }
}