SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadHauriyaFactions"
 m_sSourceDirectory "{99D577A473D7D8D7}Prefabs/Groups/HTC"
 m_bExposed 1
 m_Prefabs {
  "{04281E87CF471DE2}Prefabs/Groups/HTC/Group_HTC_RifleSquad.et"
  "{7DE3C385550AAB41}Prefabs/Groups/HTC/Group_HTC_HQ.et"
  "{B6F1C73A64911797}Prefabs/Groups/HTC/Group_HTC_Mukhabarat.et"
  "{7FA4F6FBAA569EE9}Prefabs/Groups/HTC/Group_HTC_RifleSquad_Armor.et"
 }
}