SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadHauriyaFactions"
 m_sSourceDirectory "{E33319F3EDA28898}Prefabs/Groups/HAF"
 m_bExposed 1
 m_Prefabs {
  "{193060A38945633C}Prefabs/Groups/HAF/Group_HAF_Prisoners.et"
  "{F48385848F623861}Prefabs/Groups/HAF/Group_HAF_RifleSquad.et"
  "{3D0A7E34C9F0A1D2}Prefabs/Groups/HAF/Group_HAF_HQ.et"
  "{5773AA957EE59235}Prefabs/Groups/HAF/Group_HAF_CivilianSquad.et"
 }
}