SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadHauriyaFactions"
 m_sSourceDirectory "{99D577A473D7D8D7}Prefabs/Groups/HTC"
 m_bExposed 1
 m_Prefabs {
  "{D99CAAEE2D047923}Prefabs/Vehicles/Wheeled/M1151/M1151_armed_M2HB_HAF_Black.et"
 }
}