FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{570CE64C790A3C7D}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{1AF0CAFF4A245763}Prefabs/Characters/Heads/Head_White_02_Libyan.et"
   Body "{19901FDD7FC5EE3B}Prefabs/Characters/Basebody/CharacterBasebody_Libyan.et"
  }
  VisualIdentity "{570CE64C784286B5}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{C2BC88C77F2798F7}Prefabs/Characters/Heads/Head_White_03_Libyan.et"
   Body "{19901FDD7FC5EE3B}Prefabs/Characters/Basebody/CharacterBasebody_Libyan.et"
  }
  VisualIdentity "{570CFDC06CAAD480}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{4EB885B8A7F89B3D}Prefabs/Characters/Heads/Head_White_04_Libyan.et"
   Body "{19901FDD7FC5EE3B}Prefabs/Characters/Basebody/CharacterBasebody_Libyan.et"
  }
  VisualIdentity "{570CFDC05A2BFCE8}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{96F4C78092FB54A9}Prefabs/Characters/Heads/Head_White_05_Libyan.et"
   Body "{19901FDD7FC5EE3B}Prefabs/Characters/Basebody/CharacterBasebody_Libyan.et"
  }
  VisualIdentity "{570CFDC037CCBCD3}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{BCD0E02364153286}Prefabs/Characters/Heads/Head_White_06_Libyan.et"
   Body "{19901FDD7FC5EE3B}Prefabs/Characters/Basebody/CharacterBasebody_Libyan.et"
  }
  VisualIdentity "{570CFDC1C8B17A43}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{E6281B377C410381}Prefabs/Characters/Heads/Head_White_08_Libyan.et"
   Body "{19901FDD7FC5EE3B}Prefabs/Characters/Basebody/CharacterBasebody_Libyan.et"
  }
  VisualIdentity "{697736E3255B6932}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{3E64590F4942CC15}Prefabs/Characters/Heads/Head_White_09_Libyan.et"
   Body "{19901FDD7FC5EE3B}Prefabs/Characters/Basebody/CharacterBasebody_Libyan.et"
  }
  VisualIdentity "{697736E322EAA0B9}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{7C7EC4F1913C636B}Prefabs/Characters/Heads/Head_White_10_Libyan.et"
   Body "{19901FDD7FC5EE3B}Prefabs/Characters/Basebody/CharacterBasebody_Libyan.et"
  }
 }
 SoundIdentityArray {
  SoundIdentity "{6973312D198D5148}" {
   VoiceID 202
   VoicePitch 0
  }
  SoundIdentity "{6973312D198D5171}" {
   VoiceID 201
   VoicePitch 1
  }
  SoundIdentity "{6973312D198D5170}" {
   VoiceID 202
   VoicePitch -0.9
  }
  SoundIdentity "{6973312D198D5173}" {
   VoiceID 201
   VoicePitch 0
  }
  SoundIdentity "{6973312D198D5172}" {
   VoiceID 202
   VoicePitch 0.9
  }
  SoundIdentity "{6973312D198D5175}" {
   VoiceID 202
   VoicePitch -0.9
  }
 }
 SocialIdentity SocialIdentity "{6973312D198D5174}" {
  NamesConfig {
   "Amir"
   "Hakim"
   "Karim"
   "Malik"
   "Nadir"
   "Rami"
   "Samir"
   "Tariq"
   "Yasin"
   "Ziad"
   "Anwar"
   "Basim"
   "Fadil"
   "Hamza"
   "Idris"
   "Jalil"
   "Marwan"
   "Qasim"
   "Rashid"
   "Saif"
   "Waleed"
   "Zaki"
  }
  SurnamesConfig {
   "Al-Farsi"
   "Al-Mansouri"
   "Al-Rashid"
   "Al-Tamimi"
   "Khalifa"
   "Najjar"
   "Hashimi"
   "Mahmoud"
   "Sabbagh"
   "Khatib"
   "Husseini"
   "Wacks"
   "Mutairi"
   "Jabri"
   "Al-Dabbagh"
   "Al-Bakri"
   "Al-Fayez"
  }
 }
}