FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{570CE64C790A3C7D}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{04F4D8CBA36A534B}Prefabs/Characters/Heads/Head_Black_02.et"
   Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  VisualIdentity "{570CE64C784286B5}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{E62BC538B471D41F}Prefabs/Characters/Heads/Head_White_03_tk.et"
   Body "{AABB78B5B9C32D0B}Prefabs/Characters/Basebody/CharacterBasebody_tk.et"
  }
  VisualIdentity "{570CFDC06CAAD480}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{521AA2D2EC3ABB3D}Prefabs/Characters/Heads/Head_White_03_Old_tk.et"
   Body "{AABB78B5B9C32D0B}Prefabs/Characters/Basebody/CharacterBasebody_tk.et"
  }
  VisualIdentity "{570CFDC05A2BFCE8}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{21E755A541279713}Prefabs/Characters/Heads/Head_White_02_tk.et"
   Body "{AABB78B5B9C32D0B}Prefabs/Characters/Basebody/CharacterBasebody_tk.et"
  }
  VisualIdentity "{570CFDC037CCBCD3}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{F9C435EE6E40C096}Prefabs/Characters/Heads/Head_White_06_tk.et"
   Body "{AABB78B5B9C32D0B}Prefabs/Characters/Basebody/CharacterBasebody_tk.et"
  }
  VisualIdentity "{570CFDC1C8B17A43}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{1E38B408F545BE01}Prefabs/Characters/Heads/Head_White_08_tk.et"
   Body "{AABB78B5B9C32D0B}Prefabs/Characters/Basebody/CharacterBasebody_tk.et"
  }
 }
 SoundIdentityArray {
  SoundIdentity "{6973312D198D5148}" {
   VoiceID 202
   VoicePitch 0
  }
  SoundIdentity "{6973312D198D5171}" {
   VoiceID 201
   VoicePitch 1
  }
  SoundIdentity "{6973312D198D5170}" {
   VoiceID 202
   VoicePitch -0.9
  }
  SoundIdentity "{6973312D198D5173}" {
   VoiceID 201
   VoicePitch 0
  }
  SoundIdentity "{6973312D198D5172}" {
   VoiceID 202
   VoicePitch 0.9
  }
  SoundIdentity "{6973312D198D5175}" {
   VoiceID 202
   VoicePitch -0.9
  }
 }
 SocialIdentity SocialIdentity "{6973312D198D5174}" {
  NamesConfig {
   "Amir"
   "Hakim"
   "Karim"
   "Malik"
   "Nadir"
   "Rami"
   "Samir"
   "Tariq"
   "Yasin"
   "Ziad"
   "Anwar"
   "Basim"
   "Fadil"
   "Hamza"
   "Idris"
   "Jalil"
   "Marwan"
   "Qasim"
   "Rashid"
   "Saif"
   "Waleed"
   "Zaki"
  }
  SurnamesConfig {
   "Al-Farsi"
   "Al-Mansouri"
   "Al-Rashid"
   "Al-Tamimi"
   "Khalifa"
   "Najjar"
   "Hashimi"
   "Mahmoud"
   "Sabbagh"
   "Khatib"
   "Husseini"
   "Wacks"
   "Mutairi"
   "Jabri"
   "Al-Dabbagh"
   "Al-Bakri"
   "Al-Fayez"
  }
 }
}